import {
  FOLLOW_DOCUMENT_PATH,
  MANAGE_DOC_PATH,
  MANAGE_USER_PATH,
  RECYCLE_PATH,
  REPORT_DELETE_PATH,
  REPORT_RECYCLE_PATH,
  REPORT_UPDATE_DOC_PATH,
  REPORT_UPLOAD_DOC_PATH,
  REPORT_VERSION_DOC_PATH,
} from "../paths";

export const ADMIN: string[] = [
  MANAGE_DOC_PATH,
  MANAGE_USER_PATH,
  RECYCLE_PATH,
  FOLLOW_DOCUMENT_PATH,
  "#",
  REPORT_RECYCLE_PATH,
  REPORT_DELETE_PATH,
  REPORT_UPDATE_DOC_PATH,
  REPORT_UPLOAD_DOC_PATH,
  REPORT_VERSION_DOC_PATH,
];

export const PROJECT_MANAGER: string[] = [
  MANAGE_DOC_PATH,
  FOLLOW_DOCUMENT_PATH,
  RECYCLE_PATH,
  "#",
  REPORT_RECYCLE_PATH,
  REPORT_DELETE_PATH,
  REPORT_UPDATE_DOC_PATH,
  REPORT_UPLOAD_DOC_PATH,
  REPORT_VERSION_DOC_PATH,
];

export const USER: string[] = [MANAGE_DOC_PATH, RECYCLE_PATH];

export const HR: string[] = [MANAGE_DOC_PATH,MANAGE_USER_PATH, RECYCLE_PATH];
